### PR TITLE
add a webserver to keep the bot alive

### PR DESCRIPTION
**Pull request by Beatso**
if you host with something like repl.it that automatically shuts down, you can use uptime robot to just ping this webserver

### CODE REVIEW

**Comment by Chromus-dev** [comment]
Can you help me set this up

**Comment by Chromus-dev** [comment]
Also there are conflicts that need to be fixed

**Comment by Beatso** [comment]
> Can you help me set this up
@Chromus-dev the hosting? sure

**Comment by Beatso** [comment]
@Chromus-dev conflicts have been resolved again

**Comment by Beatso** [comment]
this is unnecessary now that you have server.js

**Pull request closed without merging**
